version: "3"

name: dormitery-webase
services:
  postgres:
    image: postgres:latest
    container_name: database
    restart: always
    environment:
      POSTGRES_DB: dormitery_db
      POSTGRES_USER: dormitery_db_usr
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    networks:
      - dorm-network

networks:
  dorm-network:
    name: dorm-network
    driver: bridge